
package webPack.serv;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * SPSU Computer Related Degree Web Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SPSUDegreeDetailWebService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://localhost/SPSUDegreeService/Service.asmx?wsdl")
public class SPSUDegreeDetailWebService
    extends Service
{

    private final static URL SPSUDEGREEDETAILWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(webPack.serv.SPSUDegreeDetailWebService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = webPack.serv.SPSUDegreeDetailWebService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost/SPSUDegreeService/Service.asmx?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost/SPSUDegreeService/Service.asmx?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SPSUDEGREEDETAILWEBSERVICE_WSDL_LOCATION = url;
    }

    public SPSUDegreeDetailWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SPSUDegreeDetailWebService() {
        super(SPSUDEGREEDETAILWEBSERVICE_WSDL_LOCATION, new QName("http://tempuri.org/", "SPSUDegreeDetailWebService"));
    }

    /**
     * 
     * @return
     *     returns SPSUDegreeDetailWebServiceSoap
     */
    @WebEndpoint(name = "SPSUDegreeDetailWebServiceSoap")
    public SPSUDegreeDetailWebServiceSoap getSPSUDegreeDetailWebServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "SPSUDegreeDetailWebServiceSoap"), SPSUDegreeDetailWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SPSUDegreeDetailWebServiceSoap
     */
    @WebEndpoint(name = "SPSUDegreeDetailWebServiceSoap")
    public SPSUDegreeDetailWebServiceSoap getSPSUDegreeDetailWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "SPSUDegreeDetailWebServiceSoap"), SPSUDegreeDetailWebServiceSoap.class, features);
    }

}
